name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Published:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: setup.Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./MakePipline.sln

      - name: Build
        run: dotnet build ./MakePipline.sln --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish ./MakePipeline.sln --configuration Release --no-build --output /tmp/publish
          if [ $? -ne 0 ]; then
            echo "Error: dotnet publish command failed."
            exit 1
          fi
          publish_dir=$(realpath /tmp/publish)
          echo "Publish Directory: $publish_dir"
        
      - name: Deploy to SmarterASP.NET
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: 'https://win5066.site4now.net:8172/MsDeploy.axd?site=makepiplin-001-site1'
          username: 'makepiplin-001'
          password: 'Aa@12345'
          server-dir: '/www/makepipline/'  # Replace with your target directory on the server
          local-dir: $publish_dir # Replace with the path to your published artifacts
