name: Publish and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Published:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./MakePipline.sln

      - name: Build
        run: dotnet build ./MakePipline.sln --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish ./MakePipeline.sln --configuration Release --no-build --output /tmp/publish

      - name: Display Publish Directory
        run: echo "Publish Directory: ${{ env.PUBLISH_DIR }}"

      - name: Deploy to SmarterASP.NET
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: 'https://win5066.site4now.net:8172/MsDeploy.axd?site=makepiplin-001-site1'
          username: 'makepiplin-001'
          password: 'Aa@12345'
          server-dir: '/www/makepipline/'  # Replace with your target directory on the server
          local-dir: ${{ env.PUBLISH_DIR }} # Replace with the path to your published artifacts
